services:
  fe-prod:
    image: ${DOCKERHUB_USERNAME}/anngon-frontend:latest
    restart: always
    networks: [ web-network ]

  be-prod:
    image: ${DOCKERHUB_USERNAME}/anngon-backend:latest
    env_file: .env.prod # Chứa MONGODB_URI=mongodb+srv://... (Trỏ tới DB 'my_app_prod' trên Atlas)
    restart: always
    networks: [ web-network ]

networks:
  web-network:
    external: true
