# 98b4b67cf4655075924cf902ebb716ecd3269d8e85d064f4f6dbc61a442dea88
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    user: root
    ports:
      - "3000:3000"
    environment:
      - VITE_BASE_API=http://localhost:8005/api
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: pnpm dev --host
    networks:
      - local-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    user: root
    ports:
      - "8005:8005"
    environment:
      - PORT=8005
    env_file:
      - ./backend/.env # Chứa MONGODB_URI=mongodb+srv://... (Trỏ tới DB 'my_app_local' trên Atlas)
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: pnpm dev
    networks:
      - local-network

networks:
  local-network:
    driver: bridge
