services:
  fe-dev:
    image: ${DOCKERHUB_USERNAME}/anngon-frontend:dev
    restart: always
    networks: [ web-network ]

  be-dev:
    image: ${DOCKERHUB_USERNAME}/anngon-backend:dev
    env_file: .env.dev # Chứa MONGODB_URI=mongodb+srv://... (Trỏ tới DB 'my_app_prod' trên Atlas)
    restart: always
    networks: [ web-network ]

networks:
  web-network:
    external: true
